// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1563328522);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1563746831);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1563328492);
user_pref("browser.laterrun.bookkeeping.sessionCount", 5);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 66);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.seen-tourset-version", 3);
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\"],\"idsInUrlbar\":[\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.startup.homepage_override.buildID", "20190401050101");
user_pref("browser.startup.homepage_override.mstone", "60.8.0");
user_pref("browser.startup.homepage_override.torbrowser.version", "9.0a4");
user_pref("browser.urlbar.placeholderName", "DuckDuckGo");
user_pref("browser.zoom.siteSpecific", false);
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("devtools.selfxss.count", 4);
user_pref("devtools.telemetry.tools.opened.version", "{\"DEVTOOLS_SCREEN_RESOLUTION_ENUMERATED_PER_USER\":\"60.8.0\"}");
user_pref("distribution.iniFile.exists.appversion", "60.8.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("dom.network.enabled", false);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 27);
user_pref("extensions.lastAppBuildId", "20190401050101");
user_pref("extensions.lastAppVersion", "60.8.0");
user_pref("extensions.lastPlatformVersion", "60.8.0");
user_pref("extensions.lastTorBrowserVersion", "9.0a4");
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.torbutton.donation_banner_countdown3", 3);
user_pref("extensions.torbutton.inserted_button", true);
user_pref("extensions.torbutton.inserted_security_level", true);
user_pref("extensions.torbutton.lastBrowserVersion", "9.0a4");
user_pref("extensions.torbutton.lastUpdateCheck", "1563328493.436");
user_pref("extensions.torbutton.noscript_inited", true);
user_pref("extensions.torbutton.pref_fixup_version", 1);
user_pref("extensions.torbutton.security_slider", 4);
user_pref("extensions.torbutton.startup", true);
user_pref("extensions.torlauncher.default_bridge_type", "");
user_pref("extensions.torlauncher.prompt_at_startup", false);
user_pref("extensions.torlauncher.torrc_fixup_version", 2);
user_pref("extensions.webextensions.uuids", "{\"{73a6fe31-595d-460b-a920-fcc0f8843232}\":\"d8a0834a-9033-4b63-b400-cb0bd763c3b0\",\"https-everywhere-eff@eff.org\":\"f63cf7e5-a8d7-4bad-ab42-b665a4b21a3e\"}");
user_pref("gecko.handlerService.migrated", true);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.webaudio.enabled", true);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.enabledCache.initialized", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.enabled", false);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.expose_full_path", false);
user_pref("security.sandbox.content.tempDirSuffix", "ccebbaa0-ff76-45e5-acfe-ffe4ccaa0932");
user_pref("toolkit.startup.last_success", 1563746797);
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
